CREATE TABLE IF NOT EXISTS managers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  role TEXT NOT NULL DEFAULT 'manager',
  password TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  notification_settings JSONB DEFAULT '{}'::jsonb
);

ALTER TABLE managers ADD COLUMN IF NOT EXISTS notification_settings JSONB DEFAULT '{}'::jsonb;
